import type { RuleDefinition } from "../prompt";

export const MCP_RULES: readonly RuleDefinition[] = [
  {
    id: "mcp-armor/tool-arg-url-no-validation",
    ruleset: "mcp-armor",
    severity: "high",
    what: "MCP tool definition accepts a `url` or `href` string argument without any URL scheme allowlist or SSRF check.",
    why: "SSRF gadget. LLM can be prompted to fetch `http://169.254.169.254/latest/meta-data` and exfiltrate cloud credentials.",
    fix: "Wrap the handler with `scanToolInput(tool, args)` from mcp-armor before dispatch, or add a scheme allowlist to the Zod schema.",
    reference: "https://github.com/carlosfevernova/mcp-armor#security",
  },
  {
    id: "mcp-armor/tool-arg-command-string",
    ruleset: "mcp-armor",
    severity: "high",
    what: "MCP tool definition accepts a free-form `command`, `shell`, `script`, or `sql` string argument.",
    why: "Command injection. The LLM can be prompted to inject `; rm -rf /` or `'; DROP TABLE users; --`.",
    fix: "Replace with a strict enum of allowed commands, or use structured Zod objects (e.g., `{ operation: enum, target: uuid }`).",
  },
  {
    id: "mcp-armor/no-lazy-tool-schemas",
    ruleset: "mcp-armor",
    severity: "medium",
    what: "MCP server registers 10+ tools without using lazy schema loading (`lazyLoadTools`).",
    why: "Every model turn sends 5-10K tokens of tool schemas. Over 20 turns = 100-200K tokens burned per agent session.",
    fix: "Wrap with `lazyLoadTools(tools)` and expose `minimal` on `ListTools`, expand full schema only in `CallTool`.",
    reference: "https://github.com/carlosfevernova/mcp-armor#lazyloadtools",
  },
  {
    id: "mcp-armor/tool-input-no-zod",
    ruleset: "mcp-armor",
    severity: "medium",
    what: "MCP tool handler receives `args: unknown` and casts directly to a type without runtime validation.",
    why: "LLM-generated arguments can be anything. Missing validation = runtime crashes or silent data corruption.",
    fix: "Use `defineTool({ input: z.object({...}), handler })` from mcp-armor. Runtime validation is automatic.",
  },
  {
    id: "mcp-armor/tool-name-not-kebab",
    ruleset: "mcp-armor",
    severity: "low",
    what: "MCP tool name uses camelCase or snake_case (e.g., `getUserData`, `get_user_data`).",
    why: "Some MCP clients enforce kebab-case; some LLMs perform worse on non-standard casing.",
    fix: "Rename to `get-user-data`. Add a compatibility alias if you can't break existing callers.",
  },
  {
    id: "mcp-armor/no-error-response-shape",
    ruleset: "mcp-armor",
    severity: "low",
    what: "MCP tool handler throws directly instead of returning a structured error response.",
    why: "The LLM cannot recover — it sees a raw exception and often gives up. Reduces agent success rate.",
    fix: "Return `{ error: { code, message, retriable: boolean } }` so the LLM can decide whether to retry or ask the user.",
  },
  {
    id: "mcp-armor/tool-description-too-terse",
    ruleset: "mcp-armor",
    severity: "info",
    what: "MCP tool description is under 20 characters or is just the tool name repeated.",
    why: "LLM won't discover when to use this tool. Kills agent success rate.",
    fix: "Write 1-3 sentences: what it does, when to use, key parameters.",
  },
  {
    id: "mcp-armor/prompt-injection-echo",
    ruleset: "mcp-armor",
    severity: "medium",
    what: "MCP tool returns user-controlled text directly to the LLM without wrapping in `<user_content>` or similar delimiter.",
    why: "Prompt injection vector. An email body or web page content can override your system prompt.",
    fix: "Wrap all untrusted text in delimiters. Add a note to the LLM to treat content inside delimiters as data, not instructions.",
  },
  {
    id: "mcp-armor/file-path-no-jail",
    ruleset: "mcp-armor",
    severity: "high",
    what: "MCP tool that reads/writes files accepts a `path` argument without validating it against a jail root.",
    why: "Path traversal. LLM can be prompted to read `../../etc/passwd` or write to arbitrary locations.",
    fix: "Resolve the path against a known root: `const safe = path.resolve(ROOT, requested); if (!safe.startsWith(ROOT)) throw;`.",
  },
  {
    id: "mcp-armor/no-fallback-on-cb-open",
    ruleset: "mcp-armor",
    severity: "low",
    what: "MCP proxy uses `CircuitBreaker` but no fallback data source when the breaker is open.",
    why: "Users see errors during recovery. If you have a cached snapshot in Postgres/KV, serve it.",
    fix: "Pass `fallback: () => loadStaleFromSupabase()` to `withArmor`.",
  },
  {
    id: "mcp-armor/tool-side-effect-not-idempotent",
    ruleset: "mcp-armor",
    severity: "medium",
    what: "MCP tool that mutates state (POST/PUT/DELETE) does not accept an `idempotencyKey` argument.",
    why: "LLM retries duplicate a purchase, message, or database write.",
    fix: "Add `idempotencyKey: z.string().optional()` and use it in your handler to dedupe.",
  },
  {
    id: "mcp-armor/handler-no-timeout",
    ruleset: "mcp-armor",
    severity: "medium",
    what: "MCP tool handler makes an outbound HTTP call without a per-request timeout.",
    why: "One slow upstream causes the whole agent session to hang for the LLM's full-context limit.",
    fix: "Use `abortableFetch(url, { timeoutMs: 5000 })` from vercel-armor.",
  },
];
