import type { RuleDefinition } from "../prompt";

export const NEXT16_RULES: readonly RuleDefinition[] = [
  {
    id: "next16/cookies-in-client-bundle",
    ruleset: "next16",
    severity: "high",
    what: "`next/headers` (cookies, headers) imported at module top-level in a file that a Client Component uses.",
    why: "Pollutes the browser bundle and breaks the build. `next/headers` is server-only.",
    fix: "Split the file into `lib/x/client.ts` (browser-safe) and `lib/x/server.ts` (server-only).",
    reference: "https://nextjs.org/docs/app/api-reference/functions/cookies",
  },
  {
    id: "next16/service-role-in-client",
    ruleset: "next16",
    severity: "high",
    what: "Supabase `service_role` key referenced in a file imported by a Client Component or by `page.tsx` without `\"use server\"`.",
    why: "Full database access exposed to the browser. Immediate credential-leak in production.",
    fix: "Move service-role usage into a Route Handler (`app/api/**/route.ts`) or Server Action file marked `\"use server\"`.",
  },
  {
    id: "next16/force-dynamic-missing",
    ruleset: "next16",
    severity: "medium",
    what: "Route Handler uses `cookies()`, `headers()`, or `req.headers` but does not export `dynamic = \"force-dynamic\"`.",
    why: "Next 16 will try to statically evaluate the route and fail at build, or serve a stale cached response in production.",
    fix: "Add `export const dynamic = \"force-dynamic\";` at the top of the file.",
  },
  {
    id: "next16/edge-runtime-node-api",
    ruleset: "next16",
    severity: "high",
    what: "File declares `runtime = \"edge\"` but imports Node.js-only APIs (`fs`, `child_process`, `crypto.createHmac`, native modules).",
    why: "Fails at deploy or crashes at cold start. Edge runtime is a V8 isolate, not Node.",
    fix: "Either switch to `runtime = \"nodejs\"` or replace the Node API with Web-standard equivalent.",
  },
  {
    id: "next16/server-action-no-use-server",
    ruleset: "next16",
    severity: "medium",
    what: "Async function passed to `<form action={...}>` or invoked from a Client Component without `\"use server\"` directive on the enclosing file or function.",
    why: "Next 16 silently converts to client-side handler and skips server execution.",
    fix: "Add `\"use server\";` at the top of the file (for module-level actions) or at the top of the function body.",
  },
  {
    id: "next16/uncached-server-fetch",
    ruleset: "next16",
    severity: "low",
    what: "`fetch()` in a Server Component or route handler without any cache directive (`cache`, `next: { revalidate }`) and with no `dynamic = \"force-dynamic\"`.",
    why: "Next 16 default is `no-store` — every page render hits the upstream. Cost surprise + slow renders.",
    fix: "Add explicit `cache: 'force-cache'` (or `next: { revalidate: N }`) OR mark route dynamic if that's intentional.",
  },
  {
    id: "next16/nextjs-cve",
    ruleset: "next16",
    severity: "high",
    what: "`next` version in package.json is vulnerable to a known CVE (< 16.3.3 has multiple disclosed issues).",
    why: "Deploying vulnerable framework versions in production violates most compliance frameworks.",
    fix: "Bump `next` to at least `16.3.3` in package.json.",
  },
  {
    id: "next16/middleware-cookies-side-effect",
    ruleset: "next16",
    severity: "medium",
    what: "`middleware.ts` reads `request.cookies` but doesn't call `NextResponse.next()` with the updated cookies object.",
    why: "Session invalidation bugs — the user sees stale auth state until a hard refresh.",
    fix: "Use the `updateSession` pattern from @supabase/ssr docs. Pass the response object explicitly.",
  },
  {
    id: "next16/route-catch-all-typing",
    ruleset: "next16",
    severity: "info",
    what: "Route Handler destructures `params` from context without awaiting (`params` is `Promise<{...}>` in Next 15+).",
    why: "TypeScript build breaks. Runtime returns `undefined` where you expected string.",
    fix: "Change signature to `async function GET(req, ctx: { params: Promise<{...}> })` and `await ctx.params`.",
  },
];
