import type { RuleDefinition } from "../prompt";

export const RESILIENCE_RULES: readonly RuleDefinition[] = [
  {
    id: "vercel-armor/no-timeout",
    ruleset: "vercel-armor",
    severity: "high",
    what: "Outbound `fetch()` to a URL that isn't a Vercel-owned host, without an `AbortSignal.timeout(...)` or `signal` param.",
    why: "Slow upstream cascades 504s. The Vercel function keeps the socket open until the platform kills it — usually 30s+.",
    fix: "Wrap with `abortableFetch(url, { timeoutMs: 5000 })` from vercel-armor, or add `signal: AbortSignal.timeout(5000)`.",
    reference: "https://github.com/carlosfevernova/vercel-armor#abortablefetch",
  },
  {
    id: "vercel-armor/no-circuit-breaker",
    ruleset: "vercel-armor",
    severity: "medium",
    what: "Route handler makes an outbound fetch to a third-party API (Stripe, Anthropic, OpenAI, external ERP) with no circuit breaker.",
    why: "One extended outage burns your function-invocation budget and cascades slow responses to every concurrent user.",
    fix: "Use `armoredRoute({ cb: getCircuitBreaker('name'), fetcher, fallback })` from vercel-armor.",
    reference: "https://github.com/carlosfevernova/vercel-armor#armoredroute",
  },
  {
    id: "vercel-armor/cache-no-store-on-getable",
    ruleset: "vercel-armor",
    severity: "medium",
    what: "Client-side `fetch(url, { cache: 'no-store' })` on a URL that could be cached with a short TTL.",
    why: "Bypasses Vercel edge cache. Same URL from 100 concurrent users = 100 function invocations instead of 1.",
    fix: "Remove `cache: 'no-store'` and rely on server-side `cache-control: s-maxage=60`.",
  },
  {
    id: "vercel-armor/timestamp-cachebuster",
    ruleset: "vercel-armor",
    severity: "medium",
    what: "URL constructed with `?_=${Date.now()}` or `?t=${Date.now()}` to force a fresh response.",
    why: "Kills request collapsing at the edge. Every request has a unique cache key, so N users = N function invocations.",
    fix: "Trust the server-side `cache-control: max-age=0, s-maxage=60, stale-while-revalidate=300`.",
  },
  {
    id: "vercel-armor/missing-stale-if-error",
    ruleset: "vercel-armor",
    severity: "low",
    what: "API route sets `cache-control` header but omits `stale-if-error`.",
    why: "Users see 5xx during upstream outage instead of the last-known-good cached response.",
    fix: "Add `stale-if-error=86400` (24h grace) to your cache-control header.",
  },
  {
    id: "vercel-armor/unbounded-promise-all",
    ruleset: "vercel-armor",
    severity: "medium",
    what: "`Promise.all` over an array of `fetch()` calls without concurrency limits (fan-out > 20).",
    why: "Saturates upstream (429s cascade) and blows past Vercel function memory limits.",
    fix: "Use `throttledMap(items, 5, fetchOne)` from vercel-armor.",
    reference: "https://github.com/carlosfevernova/vercel-armor#throttledmap",
  },
  {
    id: "vercel-armor/retry-without-backoff",
    ruleset: "vercel-armor",
    severity: "low",
    what: "Retry loop without exponential backoff or jitter — tight `for` loop with immediate retry.",
    why: "Turns a transient upstream blip into a self-DDoS.",
    fix: "Use `abortableFetch(url, { retry: { attempts: 3, baseMs: 100, jitter: 0.3 } })`.",
  },
  {
    id: "vercel-armor/no-retry-after-honor",
    ruleset: "vercel-armor",
    severity: "low",
    what: "Handling 429 responses without reading the `Retry-After` header.",
    why: "You'll get banned by the upstream (Stripe, Anthropic, GitHub) faster than needed.",
    fix: "abortableFetch already honors this; if using raw fetch, parse `res.headers.get('retry-after')`.",
  },
];
